### PR TITLE
company_leak_fix

### PR DESCRIPTION
**Pull request by ahmadali1**
issue reported at: https://stackoverflow.com/questions/58363666/graphql-ruby-scoping-in-habtm-data-leak-in-nested-query

### CODE REVIEW

**Comment by oma** [comment]
Thanks @ahmadali1. This kinda fixes the issue for the query that uses id argument. For the companies list, it will return empty transaction_logs for accountants.

This is very similar to my own solution, I add the scope to the context and pull it out. Same issue, doesn't work without argument ID.

Anyway, silly that your answer got pulled deleted on SO. Please repost your answer, this time with more code. And I'll grant you the bounty unless someone provides a better answer within the deadline.

Lastly, the intent here is to create another query (ie companyNoLeak) that fixes the leak, leaving the leaky version as a working example. This PR makes the leaky example not leaky anymore, hence useless as an example. Makes sense?

**Comment by ahmadali1** [comment]
@oma Indeed i know, its the dirtiest solution 🤞 and only make companyLeak work. Actually I am also novice to graphQl world, will try to learn graphQL and repost a cleaner PR that works for listings also. And funny thing is, I can't repost it as Question also goes on_hold 🥇 :)

**Comment by oma** [comment]
I see. The bounty was also automatically pulled then. SO moderators react on the fact that the code is not posted in the SO Q, but linked outside. I get it, I've updated it, re-added the code to the Q itself and voted for re-open. Then we'll try again @ahmadali1, I'll repost the bounty and you post the answer with code on SO, plus creating that PR ;)

**Comment by ahmadali1** [comment]
@oma please give me latest stackoverflow link that is active, I think I have made it to the solution!

**Comment by boazsegev** [comment]
@ahmadali1  - nice work.

However, IMHO, the solution is sub-optimal.

Since the filtered activity log is already returned in the root object (the company, in this case) it would be better not to send the data again in the first place.

This will save server resources (CPU time / memory), bandwidth and client memory (client CPU will take the responsibility of re-linking the objects, if needed).

IMHO, a better approach would filter out the `activityLog` field from nested objects and refuse to return it.

**Comment by ahmadali1** [comment]
@oma I have updated the PR, Now companies_leak would also work along with company_leak. You can also change query name as you want easily, I am just pasting the solution here :).

**Comment by oma** [comment]
That solution works @ahmadali1 !
It's kinda ugly in context of law of demeter, but it's the best solution yet.

I didn't want you to change the leaky example, I can't merge this PR. I wanted you to create new example, leaving the leaky one intact. Instead of explaining, I did it here so you can see what I mean: #2 

Thanks both @ahmadali1 and @boazsegev, I'm happy not being alone in this :)

**Comment by ahmadali1** [comment]
Glad that I was able to show you a way, but definitely It is not production ready example that I put here, needs refinements. Going to close my pull request! and giving you a go ahead to merge yours ✌️ 

Happy Coding my Friend!

**Comment by oma** [comment]
You too! I think I'll build some examples using the feedback from @boazsegev above and Myst on SO. Basically reducing the nesting level and building more specific endpoints, though that makes it feel REST-ish. I don't mind, it's what I'm used too, but trying to learn the GraphQL way here.

The SO Q is downvoted, on-hold, your answer deleted by someone else. I got tons of points on shallow super-simple Qs and As, but this one, which is actually hard, get slaughtered. Funny how that works, it works, I can handle some downvotes as long as they keep it up. I would've been happy if I had found a thread like that.

**Comment by boazsegev** [comment]
FYI, Myst (on SO) and @boazsegev are one and the same... just in case you count my single opinion as two.

**Comment by oma** [comment]
@ahmadali1 bounty is up again: https://stackoverflow.com/questions/58363666/graphql-ruby-scoping-in-habtm-data-leak-in-nested-query Repost your answer :)

**Pull request closed without merging**
